# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_bonding.test.ipynb.

# %% auto 0
__all__ = ['test_attractive_force']

# %% ../../nbs/02_bonding.test.ipynb 3
import pytest

# %% ../../nbs/02_bonding.test.ipynb 5
def test_attractive_force():
    pass
