# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pymaterial',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/pymaterial',
                'lib_path': 'pymaterial'},
  'syms': {'pymaterial.core': {'pymaterial.core.foo': ('core.html#foo', 'pymaterial/core.py')}}}