# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_atom.ipynb.

# %% auto 0
__all__ = ['Element', 'distance', 'Compound']

# %% ../nbs/01_atom.ipynb 3
import numpy as np
from numpy import linalg

from .core import *
from .unit import Unit

# %% ../nbs/01_atom.ipynb 5
class Element:
    def __init__(self, *,
                 formula: str, # the chemical formula of the element
                 charge: int = 0,
                 coordinate = None):
        
        """
        Represents an element
        
        :param charge: the overall charge of the element
        :param coordinate: the coordinate of the element
        """
        
        e = ChemFormula(formula)
        
        self.element = e.element
        self.unicode = e.unicode
        self.charge = charge
        self.coordinate = coordinate
    
    def __repr__(self):
        return self.unicode

# %% ../nbs/01_atom.ipynb 14
def distance(a, b):
    """
    The distance between vector a and vector b
    :param a: the cooridnate of a
    :param b: the coordinate of b
    :return the distance between vector a and vector b
    
    """
    return LA.norm(a - b, 2)

# %% ../nbs/01_atom.ipynb 15
class Compound:
    def __init__(self, **kwargs):
        keys = kwargs
