# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_bonding.ipynb.

# %% auto 0
__all__ = ['E_A', 'A', 'r', 'Atom', 'Molecules', 'BondingForce', 'AttractiveForce', 'RepulsiveForce', 'NetForce', 'BondingEnergy',
           'AttractiveEnergy', 'RepulsiveEnergy', 'NetEnergy']

# %% ../nbs/02_bonding.ipynb 4
import scipy
from scipy.constants import pi, epsilon_0
import sympy as smp

from .core import *

# %% ../nbs/02_bonding.ipynb 6
class Atom:
    pass

# %% ../nbs/02_bonding.ipynb 7
class Molecules:
    # def __init__(self, molecule):
    #     pass
    pass

# %% ../nbs/02_bonding.ipynb 9
class BondingForce(Molecules):
    pass

# %% ../nbs/02_bonding.ipynb 10
E_A, A, r = smp.symbols('E_A A r')

# %% ../nbs/02_bonding.ipynb 11
#pi, epsilon_0, Z_1, Z_2, e = smp.symbols('pi epsilon_0 Z_1 Z_2 e')

# %% ../nbs/02_bonding.ipynb 17
class AttractiveForce(BondingForce):
        
    @property
    def constant_a(self):
        pass

    @property
    def coloumb_constant(self):
        unit = ureg.newton * ((ureg.meter**2)/(ureg.coulomb**2))
        return 1/(4*pi*epsilon_0) * unit
        
    def magnitude(self, charge_1, charge_2, interatomic_distance):
        """
        The attractive force between two atoms
        
        :param charge_1: the electric charge of the first atom
        :param charge_2: the electric charge of the second atom
        :param interatomic_distance: the interatomic distance between two atoms
        :return the magnitude of the attractive force between two atoms
        """
        
        charge_magnitude = abs(charge_1.to('coulomb')) * abs(charge_1.to('coulomb'))
        interatomic_distance = interatomic_distance.to('meter')
        
        return self.coloumb_constant * (charge_magnitude)/(interatomic_distance**2)

# %% ../nbs/02_bonding.ipynb 18
class RepulsiveForce(BondingForce):
    @property
    def constant_b(self):
        pass
    
    @property
    def magnitude(self, atom_1, atom_2):
        pass

# %% ../nbs/02_bonding.ipynb 19
class NetForce(BondingForce):
    @property
    def magnitude(self):
        """
        The magnitude of bonding force between two atoms in the molecule
        """
        pass

# %% ../nbs/02_bonding.ipynb 21
class BondingEnergy(Molecules):
    pass

# %% ../nbs/02_bonding.ipynb 22
class AttractiveEnergy(BondingEnergy):
    @property
    def magnitude(self):
        """
        The magnitude of the energy of the attractive force between two atoms in the molecule
        """
        pass

# %% ../nbs/02_bonding.ipynb 23
class RepulsiveEnergy(BondingEnergy):
    @property
    def magnitude(self):
        pass

# %% ../nbs/02_bonding.ipynb 24
class NetEnergy(BondingEnergy):
    @property
    def magnitude(self):
        """
        The energy of the net bonding force between two atoms in the molecule
        """
        pass
