# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ureg', 'Q', 'calculate_energy']

# %% ../nbs/00_core.ipynb 5
import pint
import sympy as smp
from scipy.constants import Rydberg, h, c, physical_constants

from .unit import Unit
from fastcore.test import test_eq

# %% ../nbs/00_core.ipynb 7
ureg = pint.UnitRegistry(system='SI')
Q = ureg.Quantity # quantity

# %% ../nbs/00_core.ipynb 32
def calculate_energy(**kwargs):
    
    keys = kwargs.keys()
    
    if 'frequency' in keys:
        return h * kwargs['frequency']
    elif 'wavelength' in kwargs:
        return (h * c)/kwargs['wavelength']
