# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_material.ipynb.

# %% auto 0
__all__ = ['Material']

# %% ../nbs/03_material.ipynb 4
from .bonding import *

# %% ../nbs/03_material.ipynb 5
class Material:
    pass
