# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_unit.ipynb.

# %% auto 0
__all__ = ['Unit']

# %% ../nbs/00_unit.ipynb 4
from dataclasses import dataclass

# %% ../nbs/00_unit.ipynb 5
@dataclass
class Unit:
    # SI Unit
    LENGTH = 'meter'
    MASS = 'kilogram'
    TIME = 'second'
    
    # Derived from SI Unit
    FORCE = 'newton'
    ELECTRIC_CHARGE = 'coulomb'
    ELECTRIC_POTENTIAL = 'volt'
    ENERGY = 'joule'
